//
//  VariablesProtocolGenerator.swift
//  TemplateVariablesDefinition
//
//  Renders the variables protocol + `__value(of:inputs:)` dispatch seam for one `variables.yaml`.
//  The `__value(of:inputs:)` extension is a public contract: code generated by other generators calls it verbatim. Changing its signature or switch semantics is a breaking change.
//

import Foundation

public struct VariablesProtocolGenerator: Sendable {
    let protocolName: String
    let variables: [VariableDefinition]

    public init(protocolName: String, variables: [VariableDefinition]) {
        self.protocolName = protocolName
        self.variables = variables
    }

    public func render(accessLevel: TemplateAccessLevel) -> [String] {
        let access = accessLevel.rawValue
        let sortedVariables = variables.sorted { $0.name < $1.name }

        var lines: [String] = []

        // 1. The protocol.
        var protocolLines = ["\(access) protocol \(protocolName): Sendable {"]
        for variable in sortedVariables {
            protocolLines.append("    func \(Self.lowerCamel(variable.name))(\(Self.parameterList(variable.inputs))) async throws -> String")
        }
        protocolLines.append("}")
        lines.append(protocolLines.joined(separator: "\n"))

        // 2. VariablesRuntimeError — emitted once.
        lines.append("""
\(access) enum VariablesRuntimeError: Error, Equatable, Sendable {
    case missingInput(placeholder: String, input: String)
    case unknownPlaceholder(String)
}
""")

        // 3. The dispatch seam. NOTE: the extension itself is emitted unmodified (no access
        // modifier) — `public extension Foo` implicitly applies the access level to its members,
        // which is fine here in isolation, but putting the access level explicitly on `__value`
        // avoids relying on that implicit-access behavior and keeps the emitted extension
        // syntactically identical regardless of accessLevel. Semantics are unchanged either way.
        var seamLines = ["extension \(protocolName) {"]
        seamLines.append("    \(access) func __value(of placeholder: String, inputs: [String: String]) async throws -> String {")
        seamLines.append("        switch placeholder {")
        for variable in sortedVariables {
            seamLines.append("        case \"\(variable.placeholder)\":")
            for input in variable.inputs {
                seamLines.append(
                    "            guard let \(input.name) = inputs[\"\(input.name)\"] else " +
                    "{ throw VariablesRuntimeError.missingInput(placeholder: \"\(variable.placeholder)\", input: \"\(input.name)\") }")
            }
            let arguments = variable.inputs.map { "\($0.name): \($0.name)" }.joined(separator: ", ")
            // `self.` qualifier is required: when a variable's name matches its sole input's
            // name, the `guard let` above binds a local constant of that name, which would
            // otherwise shadow the protocol method of the same name at this call site.
            seamLines.append("            return try await self.\(Self.lowerCamel(variable.name))(\(arguments))")
        }
        seamLines.append("        default: throw VariablesRuntimeError.unknownPlaceholder(placeholder)")
        seamLines.append("        }")
        seamLines.append("    }")
        seamLines.append("}")
        lines.append(seamLines.joined(separator: "\n"))

        return lines
    }

    private static func parameterList(_ inputs: [(name: String, type: String)]) -> String {
        inputs.map { "\($0.name): \($0.type)" }.joined(separator: ", ")
    }

    private static func lowerCamel(_ name: String) -> String {
        guard let first = name.first else { return name }
        return first.lowercased() + name.dropFirst()
    }
}
