//
//  HeaderGenerator.swift
//  DDDKit
//
//  Created by Grady Zhuo on 2025/2/11.
//

package struct HeaderGenerator {
    
    let dependencies: [String]
    
    package init(dependencies: [String]) {
        self.dependencies = dependencies
    }
    
    package func render() -> [String]{
        return [
            """
// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the event generator plugin.
//

"""
        ] + dependencies.map {
            "import \($0)"
        }
    }
}
